<?php

namespace Plugin\FormDb\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormContentRepository extends EntityRepository
{
}
